[MSVC] fix error C2995
MSVC-2015 can't handle decltype in function template argument list.
C2995: function template has already been defined. Moving decltype out
of the function fixes the problem.