Apparently the -I flag not correct because the
obvious error on line 136 is not detected by compiler:

-*- mode: compilation; default-directory: "~/prog_dev/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/" -*-
Compilation started at Fri Nov 18 17:34:32

make -f linkerr.mk run -Wtypes.cpp
/home/evansl/dwnlds/gcc/5.2.0/install/bin/g++ -c -O0    -O0 -gdwarf-2 -std=c++17 -Wall -Wno-deprecated -Wstrict-overflow -ftemplate-depth-200  -Wno-unused-local-typedefs -Wno-unused-but-set-variable  -I~/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include -I/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0    -ftemplate-depth=200  types.cpp -MMD -o ../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/types.o
types.cpp:12:19: note: #pragma message: yesdef(PARSE_RULE_BODY)
   #pragma message "yesdef(PARSE_RULE_BODY)"
                   ^
types.cpp:201:17: note: #pragma message: notdef(SEHE_TYPES_DEF_HPP_PASTE)
 #pragma message "notdef(SEHE_TYPES_DEF_HPP_PASTE)"
                 ^
types.cpp:202:17: note: #pragma message: notdef(EXPLICT_SPECIALIZATION_FROM_LINKER_ERROR_MSG)
 #pragma message "notdef(EXPLICT_SPECIALIZATION_FROM_LINKER_ERROR_MSG)"
                 ^
/home/evansl/dwnlds/gcc/5.2.0/install/bin/g++ -Wl,--library-path=/home/evansl/dwnlds/gcc/5.2.0/install/lib64 -Wl,-rpath=/home/evansl/dwnlds/gcc/5.2.0/install/lib64  ../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.o ../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/example.o ../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/types.o  -o ../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.exe
../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/example.o: In function `bool boost::spirit::x3::rule<client::parser::type_class, boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >, false>::parse<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::spirit::x3::context<boost::spirit::x3::skipper_tag, boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag> const, boost::spirit::x3::unused_type>, boost::fusion::iterator_range<boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 1>, boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 2> > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, boost::spirit::x3::context<boost::spirit::x3::skipper_tag, boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag> const, boost::spirit::x3::unused_type> const&, boost::spirit::x3::unused_type, boost::fusion::iterator_range<boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 1>, boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 2> >&) const':
/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0/boost/spirit/home/x3/nonterminal/rule.hpp:116: undefined reference to `bool client::parser::parse_rule<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::spirit::x3::context<boost::spirit::x3::skipper_tag, boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag> const, boost::spirit::x3::unused_type>, boost::fusion::iterator_range<boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 1>, boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 2> > >(boost::spirit::x3::rule<client::parser::type_class, boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >, false>, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, boost::spirit::x3::context<boost::spirit::x3::skipper_tag, boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag> const, boost::spirit::x3::unused_type> const&, boost::fusion::iterator_range<boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 1>, boost::fusion::basic_iterator<boost::fusion::struct_iterator_tag, boost::fusion::random_access_traversal_tag, client::ast::VariableDec, 2> >&)'
collect2: error: ld returned 1 exit status
/home/evansl/prog_dev/root.imk:200: recipe for target '../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.exe' failed
make: *** [../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.exe] Error 1

Compilation exited abnormally with code 2 at Fri Nov 18 17:34:35