Need another extract_rule_attr overload to handle
the following case:

types_def.hpp:32:1:   required from ‘bool client::parser::parse_rule(client::parser::type_type, Iterator&, const Iterator&, const Context&, Attribute&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; Attribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; client::parser::type_type = boost::spirit::x3::rule<client::parser::type_class, boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> > >]’
types.cpp:7:1:   required from here
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:131:43: error: no matching function for call to ‘boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType>::extract_rule_attr(boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >&) const’
             auto& e_attr=extract_rule_attr(attr);
                                           ^
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:113:9: note: candidate: static boost::spirit::x3::rule<ID, Attribute, force_attribute>::attribute_type& boost::spirit::x3::rule<ID, Attribute, force_attribute>::extract_rule_attr(boost::spirit::x3::rule<ID, Attribute, force_attribute>::attribute_type&) [with ID = client::parser::class_type_class; Attribute = client::ast::ClassType; bool force_attribute_ = false; boost::spirit::x3::rule<ID, Attribute, force_attribute>::attribute_type = client::ast::ClassType]
         extract_rule_attr
         ^
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:113:9: note:   no known conversion for argument 1 from ‘boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >’ to ‘boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType>::attribute_type& {aka client::ast::ClassType&}’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:121:9: note: candidate: template<class First, class Last> static boost::spirit::x3::rule<ID, Attribute, force_attribute>::attribute_type& boost::spirit::x3::rule<ID, Attribute, force_attribute>::extract_rule_attr(boost::fusion::iterator_range<First, Last>&) [with First = First; Last = Last; ID = client::parser::class_type_class; Attribute = client::ast::ClassType; bool force_attribute_ = false]
         extract_rule_attr
         ^
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:121:9: note:   template argument deduction/substitution failed:
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:131:43: note:   ‘boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >’ is not derived from ‘boost::fusion::iterator_range<Cur, End>’
             auto& e_attr=extract_rule_attr(attr);
                                           ^