extract_rule_attr(variant<types...>&) compiles, but
now context error :(

                 from types.cpp:1:
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/support/context.hpp: In instantiation of ‘decltype(auto) boost::spirit::x3::get(const Context&) [with Tag = client::ast::ClassType; Context = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >]’:
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:133:39:   required from ‘static boost::spirit::x3::rule<ID, Attribute, force_attribute>::attribute_type& boost::spirit::x3::rule<ID, Attribute, force_attribute>::extract_rule_attr(boost::spirit::x3::variant<Types ...>&) [with Types = {client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType>}; ID = client::parser::class_type_class; Attribute = client::ast::ClassType; bool force_attribute_ = false; boost::spirit::x3::rule<ID, Attribute, force_attribute>::attribute_type = client::ast::ClassType]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:140:43:   required from ‘bool boost::spirit::x3::rule<ID, Attribute, force_attribute>::parse(Iterator&, const Iterator&, const Context&, boost::spirit::x3::unused_type, Attribute_&) const [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; Attribute_ = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ID = client::parser::class_type_class; Attribute = client::ast::ClassType; bool force_attribute_ = false]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/core/detail/parse_into_container.hpp:101:17:   required from ‘static bool boost::spirit::x3::detail::parse_into_container_base_impl<Parser>::call_synthesize_x(const Parser&, Iterator&, const Iterator&, const Context&, RContext&, Attribute&, mpl_::false_) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; RContext = client::ast::LambdaType; Attribute = std::vector<boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> > >; Parser = boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType>; mpl_::false_ = mpl_::bool_<false>]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/core/detail/parse_into_container.hpp:132:37:   required from ‘static bool boost::spirit::x3::detail::parse_into_container_base_impl<Parser>::call_synthesize(const Parser&, Iterator&, const Iterator&, const Context&, RContext&, Attribute&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; RContext = client::ast::LambdaType; Attribute = std::vector<boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> > >; Parser = boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType>]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/core/detail/parse_into_container.hpp:187:35:   required from ‘static bool boost::spirit::x3::detail::parse_into_container_base_impl<Parser>::call_synthesize_dispatch_by_seq(const Parser&, Iterator&, const Iterator&, const Context&, RContext&, Attribute&, mpl_::false_) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; RContext = client::ast::LambdaType; Attribute = std::vector<boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> > >; Parser = boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType>; mpl_::false_ = mpl_::bool_<false>]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/core/detail/parse_into_container.hpp:196:51:   [ skipping 20 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/detail/rule.hpp:266:34:   required from ‘static bool boost::spirit::x3::detail::rule_parser<Attribute, ID>::parse_rhs_main(const RHS&, Iterator&, const Iterator&, const Context&, RContext&, ActualAttribute&) [with RHS = boost::spirit::x3::alternative<boost::spirit::x3::rule<client::parser::lambda_type_class, client::ast::LambdaType>, boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType> >; Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; RContext = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ActualAttribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; Attribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ID = client::parser::type_class]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/detail/rule.hpp:280:34:   required from ‘static bool boost::spirit::x3::detail::rule_parser<Attribute, ID>::parse_rhs(const RHS&, Iterator&, const Iterator&, const Context&, RContext&, ActualAttribute&, mpl_::false_) [with RHS = boost::spirit::x3::alternative<boost::spirit::x3::rule<client::parser::lambda_type_class, client::ast::LambdaType>, boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType> >; Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; RContext = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ActualAttribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; Attribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ID = client::parser::type_class; mpl_::false_ = mpl_::bool_<false>]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/detail/rule.hpp:332:37:   required from ‘static bool boost::spirit::x3::detail::rule_parser<Attribute, ID>::call_rule_definition(const RHS&, const char*, Iterator&, const Iterator&, const Context&, ActualAttribute&, ExplicitAttrPropagation) [with RHS = boost::spirit::x3::alternative<boost::spirit::x3::rule<client::parser::lambda_type_class, client::ast::LambdaType>, boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType> >; Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; ActualAttribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ExplicitAttrPropagation = mpl_::bool_<false>; Attribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ID = client::parser::type_class]’
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:65:39:   required from ‘bool boost::spirit::x3::rule_definition<ID, RHS, Attribute, force_attribute_>::parse(Iterator&, const Iterator&, const Context&, boost::spirit::x3::unused_type, Attribute_&) const [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; Attribute_ = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; ID = client::parser::type_class; RHS = boost::spirit::x3::alternative<boost::spirit::x3::rule<client::parser::lambda_type_class, client::ast::LambdaType>, boost::spirit::x3::rule<client::parser::class_type_class, client::ast::ClassType> >; Attribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; bool force_attribute_ = false]’
types_def.hpp:32:1:   required from ‘bool client::parser::parse_rule(client::parser::type_type, Iterator&, const Iterator&, const Context&, Attribute&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Context = boost::spirit::x3::context<boost::spirit::x3::skipper_tag, const boost::spirit::x3::char_class<boost::spirit::char_encoding::ascii, boost::spirit::x3::space_tag>, boost::spirit::x3::unused_type>; Attribute = boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >; client::parser::type_type = boost::spirit::x3::rule<client::parser::type_class, boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> > >]’
types.cpp:7:1:   required from here
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/support/context.hpp:63:48: error: no matching function for call to ‘boost::spirit::x3::variant<client::ast::nil, boost::spirit::x3::forward_ast<client::ast::LambdaType>, boost::spirit::x3::forward_ast<client::ast::ClassType> >::get(boost::mpl::identity<client::ast::ClassType>) const’
         return context.get(mpl::identity<Tag>());
                                                ^