OOPS.  Neglected the post_transform:
-*- mode: compilation; default-directory: "~/prog_dev/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/" -*-
Compilation started at Tue Nov 22 07:48:49

make -f linkerr.mk run
/home/evansl/dwnlds/gcc/5.2.0/install/bin/g++ -c -O0    -O0 -gdwarf-2 -std=c++17 -Wall -Wno-deprecated -Wstrict-overflow -ftemplate-depth-200  -Wno-unused-local-typedefs -Wno-unused-but-set-variable  -I/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include -I/home/evansl/prog_dev/boost/releases/ro/boost_1_61_0    -ftemplate-depth=200  main.cpp -MMD -o ../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.o
main.cpp:6:17: note: #pragma message: notdef(SINGLE_TU)
 #pragma message "notdef(SINGLE_TU)"
                 ^
In file included from /home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal.hpp:10:0,
                 from /home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3.hpp:17,
                 from example.hpp:4,
                 from main.cpp:12:
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:12:19: note: #pragma message: yesdef(EXAGON_ATTR_XFORM_IN_RULE)
   #pragma message "yesdef(EXAGON_ATTR_XFORM_IN_RULE)"
                   ^
In file included from /home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/rule.hpp:21:0,
                 from /home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal.hpp:10,
                 from /home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3.hpp:17,
                 from example.hpp:4,
                 from main.cpp:12:
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/detail/rule.hpp: In static member function ‘static bool boost::spirit::x3::detail::rule_parser<RuleAttribute, ID>::call_rule_definition(const RHS&, const char*, Iterator&, const Iterator&, const Context&, ActualAttribute&, ExplicitAttrPropagation)’:
/home/evansl/prog_dev/boost/github/spirit/context_debug_fix.fork/spirit/include/boost/spirit/home/x3/nonterminal/detail/rule.hpp:356:59: error: ‘transform_attr’ was not declared in this scope
                 traits::post_transform(attr, std::forward<transform_attr>(attr_));
                                                           ^
In file included from example.hpp:6:0,
                 from main.cpp:12:
ast.hpp: At global scope:
ast.hpp:14:21: note: #pragma message: yesdef(VARIABLE_DEC_OPTIONAL)
     #pragma message "yesdef(VARIABLE_DEC_OPTIONAL)"
                     ^
/home/evansl/prog_dev/root.imk:170: recipe for target '../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.o' failed
make: *** [../build/gcc5_2_0/boost/dwnlds_work/dwnlds/Exagon.linker_error_example.clone/linker_error_example/main.o] Error 1

Compilation exited abnormally with code 2 at Tue Nov 22 07:48:51